INSERT INTO "hobbies" (nama, created_at, updated_at)
            VALUES
                ('Membaca', NOW(), NOW()),
                ('Menulis', NOW(), NOW()),
                ('Coding', NOW(), NOW()),
                ('Gaming', NOW(), NOW()),
                ('Fotografi', NOW(), NOW()),
                ('Memasak', NOW(), NOW()),
                ('Bersepeda', NOW(), NOW()),
                ('Renang', NOW(), NOW()),
                ('Badminton', NOW(), NOW()),
                ('Berkebun', NOW(), NOW()),
                ('Menggambar', NOW(), NOW()),
                ('Gaming', NOW(), NOW()),
                ('Menonton film', NOW(), NOW()),
                ('Menonton anime', NOW(), NOW()),
                ('Menonton drama', NOW(), NOW()),
                ('Mendengarkan musik', NOW(), NOW()),
                ('Bernyanyi', NOW(), NOW()),
                ('Bermain gitar', NOW(), NOW()),
                ('Bermain piano', NOW(), NOW()),
                ('Lari', NOW(), NOW()),
                ('Bermain Sepak Bola', NOW(), NOW()),
                ('Bermain biola', NOW(), NOW()),
                ('Bermain drum', NOW(), NOW()),
                ('Basket', NOW(), NOW()),
                ('Voli', NOW(), NOW()),
                ('Renang', NOW(), NOW()),
                ('Bersepeda', NOW(), NOW()),
                ('Hiking', NOW(), NOW()),
                ('Camping', NOW(), NOW()),
                ('Memancing', NOW(), NOW()),
                ('Surfing', NOW(), NOW()),
                ('Skateboard', NOW(), NOW()),
                ('Roller skating', NOW(), NOW()),
                ('Yoga', NOW(), NOW()),
                ('Fitness', NOW(), NOW()),
                ('Bela diri', NOW(), NOW()),
                ('Fotografi alam', NOW(), NOW()),
                ('Traveling', NOW(), NOW()),
                ('Backpacking', NOW(), NOW()),
                ('Road trip', NOW(), NOW()),
                ('Menjahit', NOW(), NOW()),
                ('Kaligrafi', NOW(), NOW()),
                ('Golf', NOW(), NOW());